name: Deploy Pages

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pages: write
            id-token: write            
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - name: Install dependencies
              run: npm install
            - name: Install slidev
              run: npm i -g @slidev/cli
            - name: Build
              run: slidev build --base lets-webdev
            - uses: actions/configure-pages@v3
            - uses: actions/upload-pages-artifact@v1
              with:
                  path: dist
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v2
